source 'https://rubygems.org'
ruby '2.3.1'
gem 'rails', '5.0.0'
gem 'sass-rails', '5.0.5'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'turbolinks', '~> 5.x'
gem 'bootstrap-sass'
gem 'bootswatch-rails'
gem 'haml'
gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-gitlab'
gem 'omniauth-bitbucket'
gem 'pg'
gem 'pundit'
gem 'simple_form'
gem 'pronto', '~> 0.7.0'
gem 'sidekiq'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'sinatra', require: false, github: 'sinatra/sinatra'
gem 'git_diff_parser'

group :development do
  #gem 'better_errors'
  #gem 'binding_of_caller'
  gem 'web-console', '~> 3.3'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'capistrano', '~> 3.0.1'
  gem 'capistrano-bundler'
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-rails-console'
  gem 'capistrano-rvm', '~> 0.1.1'
  gem 'foreman'
  gem 'html2haml'
  gem 'rails_layout'
  gem 'spring-commands-rspec'
end

group :development, :test do
  gem 'factory_girl_rails', '4.7.0'
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-rails', '3.5.0'
  gem 'rubocop'
  gem 'reek'
  gem 'byebug'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
  gem 'webmock'
end
